apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-frontend
  template:
    metadata:
      labels:
        app: express-frontend
    spec:
      containers:
        - name: express-frontend
          image: komalguram2023/docker-frontend:v2
          env:
            - name: BACKEND_URL
              value: "http://flask-backend:5000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-frontend
spec:
  type: NodePort
  selector:
    app: express-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
